version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    networks:
      - mynet
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynet
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - mynet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    container_name: mongo-express
    networks:
      - mynet
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


networks:
  mynet:

volumes:
  mongodb-data: