version: "3"
services:
  local-eureka:
    build: ./eurekaserver
    networks:
      - mynet
    image: local-eureka
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://local-eureka:8761/eureka
  local-feign:
    build: ./feign
    networks:
      - mynet
    depends_on:
      - local-eureka
    image: local-feign
    ports:
      - "8090:8090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://local-eureka:8761/eureka
  local-demo:
    build: ./demoapp
    networks:
      - mynet
    image: local-demo
    depends_on:
      - local-eureka
    ports:
      - "8091:8091"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://local-eureka:8761/eureka
  local-mqproducer:
    build: ./mqproducer
    networks:
      - mynet
    image: local-mqproducer
    depends_on:
      - local-eureka
    ports:
      - "8092:8092"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://local-eureka:8761/eureka
  local-mqconsumer:
    build: ./mqconsumer
    networks:
      - mynet
    image: local-mqconsumer
    depends_on:
      - local-eureka
      - local-mqproducer
    ports:
      - "8093:8093"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://local-eureka:8761/eureka
  local-gateway:
    build: ./gateway
    networks:
      - mynet
    image: local-gateway
    depends_on:
      - local-eureka
    ports:
      - "8094:8094"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://local-eureka:8761/eureka

networks:
  mynet:
    driver: bridge