server:
  port: 8761

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: eurekaserver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false