server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: demo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka