server:
  port: 8091

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: demo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka