server:
  port: 8093

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: localhost
    port: 5672
  application:
    name: mqconsumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

mqconsumer-properties:
  queue: test-queue